### ISSUE TITLE
 Styling blog and events section

### ISSUE THREAD

**Issue by liamcan** [Cannold/cannold.com#31]
We would like our blog and events section to more closely replicate ghosts layout e.g each post should be a 'tile' and closely resemble ghosts tiles like so:

![Screen Shot 2019-09-05 at 1 01 39 pm](https://user-images.githubusercontent.com/24725093/64314589-d7bc7c00-cff2-11e9-8224-c6671132ffb5.png)

rather than looking how they do now:

![Screen Shot 2019-09-05 at 1 02 42 pm](https://user-images.githubusercontent.com/24725093/64314602-e86cf200-cff2-11e9-8da2-8c9b0f2a35d0.png)

White on a black background would be preferable to mostly closely resemble ghosts layout

**Comment by adamc00** [comment]
Quick note. No need for the tag (grey small heading at top), avatar, or reading time to appear.

**Comment by huwmillar** [comment]
Fixed, site needs to be redeployed.
